name: Slashdot DIYgest Email

on:
  schedule:
    - cron: "0,5,10,15,30 1 * * *"

  workflow_dispatch:

jobs:
  Slashdot-DIYgest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Quit when email already sent"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
         SUCCESS_TODAY=$(gh run list \
                         --created $(TZ=Asia/Bangkok date +%Y-%m-%d) \
                         -s success \
                         --json "status,startedAt" \
                         --workflow slashdot-diygest-email.yml \
                         -t '{{range .}}{{tablerow .startedAt .status}}{{end}}' | wc -l)

         if [[ $SUCCESS_TODAY > 0 ]]; then
           echo "## Email already sent today, skip workflow" >> "$GITHUB_STEP_SUMMARY"
           echo "CANCEL_RUN=true" >> "$GITHUB_ENV"
         else
           echo "## Email not sent today, continue workflow" >> "$GITHUB_STEP_SUMMARY"
         fi

      - name: Cache Go deps
        if: ${{ ! env.CANCEL_RUN  == 'true' }}
        uses: gacts/setup-go-with-cache@v1
        with:
          go-version: 1.19

      - name: Install Golang deps
        if: ${{ ! env.CANCEL_RUN  == 'true' }}
        run: |
          go install github.com/cbroglie/mustache/cmd/mustache@latest
          go install github.com/ericchiang/pup@latest

      - name: Scrape
        if: ${{ ! env.CANCEL_RUN  == 'true' }}
        run: |
          bin/slashdot_scrape.sh
          echo "HTMLFILE=$(ls *html)" >> "$GITHUB_ENV"
          echo "JSONFILE=$(ls *json)" >> "$GITHUB_ENV"

      - name: Email Slashdot DIYgest
        if: ${{ ! env.CANCEL_RUN  == 'true' }}
        id: sending_email
        uses: dawidd6/action-send-mail@v3
        with:
          subject: Slashdot DIYGest
          from: Slashdot DIYgest
          to: ${{secrets.GMAIL_USER}}
          username: ${{secrets.GMAIL_USER}}
          password: ${{secrets.GM_APPWRD}}
          html_body: file://${{ env.HTMLFILE }}
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          ignore_cert: true
          priority: high
          attachments: ${{ env.JSONFILE }}
