name: Slashdot DIYgest Email

on:
  schedule:
    - cron: "0,15,30,45 1 * * *"

  workflow_dispatch:

jobs:
  Slashdot-DIYgest:
    runs-on: ubuntu-latest
    steps:
      - name: "Has Slashdot-DIYgest been sent today?"
        run: bin/check_already_sent.sh

      - name: Checkout code
        if: ${{ env.RUN }}
        uses: actions/checkout@v3

      - name: Cache Go deps
        if: ${{ env.RUN }}
        uses: gacts/setup-go-with-cache@v1
        with:
          go-version: 1.19

      - name: Install Golang deps
        if: ${{ env.RUN }}
        run: |
          go install github.com/cbroglie/mustache/cmd/mustache@latest
          go install github.com/ericchiang/pup@latest

      - name: Scrape
        if: ${{ env.RUN }}
        run: |
          bin/slashdot_scrape.sh
          echo "HTMLFILE=$(ls *html)" >> "$GITHUB_ENV"
          echo "JSONFILE=$(ls *json)" >> "$GITHUB_ENV"

      - name: Email Slashdot DIYgest
        if: ${{ env.RUN }}
        id: sending_email
        uses: dawidd6/action-send-mail@v3
        with:
          subject: Slashdot DIYGest
          from: Slashdot DIYgest
          to: ${{secrets.GMAIL_USER}}
          username: ${{secrets.GMAIL_USER}}
          password: ${{secrets.GM_APPWRD}}
          html_body: file://${{ env.HTMLFILE }}
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          ignore_cert: true
          priority: high
          attachments: ${{ env.JSONFILE }}
